[package]
name = "bank-account"
version = "0.1.0"

[lib]
path = "src/lib.rs"
kind = "account-component"
namespace = "miden:bank-account/bank@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
